spring.application.name=web
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=webroot
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.freemarker.expose-request-attributes=true